files:
  file_name: AAPL.parquet
paths:
  train_data: ./data/prepared/train
  test_data: ./data/prepared/test
  infer_data: ./data/prepared/infer
  model: ./models


params:
  loss_function: RMSE
  n_estimators: 1000
  learning_rate: 0.03
  depth: 6
  l2_leaf_reg: 2
